version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm ci || npm install

  pre_build:
    commands:
      - echo Running pre-build checks...
      - echo Checking node version: $(node --version)
      - echo Checking npm version: $(npm --version)

  build:
    commands:
      - echo Build started on `date`
      - npm run build || echo "No build script found, skipping build step"

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Preparing for Elastic Beanstalk deployment
      - aws elasticbeanstalk describe-environments --environment-names $ELASTIC_BEANSTALK_ENV || echo "Setting up EB deployment"
      - echo Creating application bundle
      - zip -r deploy.zip . -x "*.git*" -x "terraform/*" -x "scripts/*" -x "lambda-functions/*" -x "lambda/*"
      - echo Deploying to Elastic Beanstalk
      - aws s3 cp deploy.zip s3://$ARTIFACT_BUCKET/deploy-$CODEBUILD_BUILD_NUMBER.zip
      - aws elasticbeanstalk create-application-version --application-name $ELASTIC_BEANSTALK_APP --version-label v-$CODEBUILD_BUILD_NUMBER --source-bundle S3Bucket=$ARTIFACT_BUCKET,S3Key=deploy-$CODEBUILD_BUILD_NUMBER.zip
      - aws elasticbeanstalk update-environment --environment-name $ELASTIC_BEANSTALK_ENV --version-label v-$CODEBUILD_BUILD_NUMBER

artifacts:
  files:
    # Include all files needed for Elastic Beanstalk deployment
    - server.js
    - database.js
    - schema.js
    - email-service.js
    - scheduled-events-api.js
    - package.json
    - package-lock.json
    - next.js-frontend/**/*
    - src/**/*
    - deploy/**/*
    - .ebextensions/**/*
    - node_modules/**/*
    - Procfile
    - .platform/**/*
    - README.md
    # Any other files required for your application
  base-directory: '.'
  discard-paths: no

cache:
  paths:
    - 'node_modules/**/*'