AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for Visitor Sign-In Application using CodePipeline with GitHub'

Parameters:
  AppName:
    Description: Name of the application
    Type: String
    Default: visitor-sign-in-app
  
  EnvironmentName:
    Description: Name of the environment
    Type: String
    Default: production
    AllowedValues:
      - production
      - staging
      - development
  
  GitHubOwner:
    Description: GitHub repository owner
    Type: String
  
  GitHubRepo:
    Description: GitHub repository name
    Type: String
  
  GitHubBranch:
    Description: GitHub repository branch
    Type: String
    Default: main
  
  GitHubConnectionArn:
    Description: ARN of the CodeStar Connection to GitHub (can be provided after manual activation)
    Type: String
    Default: ""
  
  ElasticBeanstalkApplicationName:
    Description: Name of the Elastic Beanstalk application
    Type: String
    Default: visitor-sign-in-app
  
  ElasticBeanstalkEnvironmentName:
    Description: Name of the Elastic Beanstalk environment
    Type: String
    Default: visitor-sign-in-app-production
  
  DatabasePassword:
    Description: Password for the PostgreSQL database
    Type: String
    NoEcho: true
  
  DatabaseName:
    Description: Name of the PostgreSQL database
    Type: String
    Default: visitor_app
    
  DatabaseUsername:
    Description: Username for the PostgreSQL database
    Type: String
    Default: postgres
    
  DatabasePort:
    Description: Port for the PostgreSQL database
    Type: String
    Default: 5432
  
  EmailServiceEnabled:
    Description: Enable email notifications for visitor sign-ins and event registrations
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
  
  SessionSecret:
    Description: Secret for session encryption
    Type: String
    NoEcho: true
    Default: "visitor-app-session-secret-change-in-production"
  
  ArtifactBucketName:
    Description: Name of the S3 bucket for build artifacts
    Type: String
    Default: visitor-app-artifacts
    
  CreateArtifactBucket:
    Description: Whether to create a new S3 artifact bucket (set to false if bucket already exists)
    Type: String
    Default: "false"
    AllowedValues:
      - "true"
      - "false"

  PlatformVersion:
    Description: Platform version for Elastic Beanstalk
    Type: String
    Default: "Node.js 20"

  InstanceType:
    Description: EC2 instance type for Elastic Beanstalk
    Type: String
    Default: t3.small
    AllowedValues:
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large

Conditions:
  ShouldCreateArtifactBucket: !Equals [!Ref CreateArtifactBucket, 'true']

Resources:
  # S3 Bucket for build artifacts
  # Note: This bucket is expected to already exist, created by the deployment script
  # The bucket will only be created if CreateArtifactBucket is set to 'true'
  # DeletionPolicy and UpdateReplacePolicy are set to Retain to avoid issues with bucket recreation
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Condition: ShouldCreateArtifactBucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Ref ArtifactBucketName
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
        
  # Handle the case for an existing S3 bucket without trying to create it in CloudFormation
  # This is a much simpler approach than creating a custom resource
  # We'll just reference the bucket name directly in the Pipeline since we know it exists
  
  # IAM Roles
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
      Policies:
        - PolicyName: !Sub ${AppName}-ecr-access-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'ecr:BatchCheckLayerAvailability'
                  - 'ecr:CompleteLayerUpload'
                  - 'ecr:GetAuthorizationToken'
                  - 'ecr:InitiateLayerUpload'
                  - 'ecr:PutImage'
                  - 'ecr:UploadLayerPart'
                  - 'ecr:BatchGetImage'
                  - 'ecr:GetDownloadUrlForLayer'
                  - 'ecr:CreateRepository'
                  - 'ecr:DescribeRepositories'
                  - 'ecr:ListImages'
                  - 'ecr:DeleteRepository'
                  - 'ecr:TagResource'
                  # Elastic Beanstalk permissions
                  - 'elasticbeanstalk:CreateApplicationVersion'
                  - 'elasticbeanstalk:UpdateEnvironment'
                  - 'elasticbeanstalk:DescribeEnvironments'
                  - 'elasticbeanstalk:DescribeApplications'
                  - 'elasticbeanstalk:DescribeEvents'
                  - 'elasticbeanstalk:CheckDNSAvailability'
                Resource: '*'
  
  # We've removed the CodePipeline role since we're bypassing the pipeline
  
  # We don't need the CodeStar connections policy since we're using OAuth
  
  # CodeBuild Project
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${AppName}-build
      Description: 'Build project for visitor sign-in application'
      ServiceRole: !Ref CodeBuildServiceRole
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        PrivilegedMode: false
        EnvironmentVariables:
          - Name: DEPLOY_STAGE
            Value: !Ref EnvironmentName
          - Name: DATABASE_PASSWORD
            Value: !Ref DatabasePassword
          - Name: DATABASE_NAME
            Value: !Ref DatabaseName
          - Name: DATABASE_USERNAME
            Value: !Ref DatabaseUsername
          - Name: DATABASE_PORT
            Value: !Ref DatabasePort
          - Name: SESSION_SECRET
            Value: !Ref SessionSecret
          - Name: EMAIL_SERVICE_ENABLED
            Value: !Ref EmailServiceEnabled
          # Variables for Elastic Beanstalk deployment
          - Name: ELASTIC_BEANSTALK_APP
            Value: !Ref ElasticBeanstalkApplicationName
          - Name: ELASTIC_BEANSTALK_ENV
            Value: !Ref ElasticBeanstalkEnvironmentName
          - Name: ARTIFACT_BUCKET
            Value: !Ref ArtifactBucketName
      Source:
        Type: GITHUB
        Location: !Sub https://github.com/${GitHubOwner}/${GitHubRepo}.git
        BuildSpec: buildspec.yml
        GitCloneDepth: 1
        Auth:
          Type: OAUTH
      TimeoutInMinutes: 15
  
  # Create Elastic Beanstalk application if it doesn't exist
  ElasticBeanstalkApplication:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      ApplicationName: !Ref ElasticBeanstalkApplicationName
      Description: !Sub "Elastic Beanstalk Application for ${AppName}"

  # Create Elastic Beanstalk environment
  ElasticBeanstalkEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName: !Ref ElasticBeanstalkApplication
      EnvironmentName: !Ref ElasticBeanstalkEnvironmentName
      SolutionStackName: !Sub "64bit Amazon Linux 2 v5.8.0 running ${PlatformVersion}"
      OptionSettings:
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: InstanceType
          Value: !Ref InstanceType
        
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: NODE_ENV
          Value: !Ref EnvironmentName
        
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: DATABASE_NAME
          Value: !Ref DatabaseName
        
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: DATABASE_USERNAME
          Value: !Ref DatabaseUsername
        
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: DATABASE_PASSWORD
          Value: !Ref DatabasePassword
        
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: DATABASE_PORT
          Value: !Ref DatabasePort
        
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: SESSION_SECRET
          Value: !Ref SessionSecret
        
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: EMAIL_SERVICE_ENABLED
          Value: !Ref EmailServiceEnabled

  # We'll use OAuth authentication for GitHub directly with CodeBuild
  # No need for a CodeStar connection when using direct OAUTH integration

  # Simplified approach: We'll create a manual trigger for CodeBuild
  # This will bypass the complex pipeline configuration that's causing validation errors
  # Instead, we'll provide instructions for manually triggering builds after GitHub connection is set up

Outputs:
  CodeBuildProjectURL:
    Description: URL to the CodeBuild project console
    Value: !Sub https://console.aws.amazon.com/codesuite/codebuild/projects/${AppName}-build/history?region=${AWS::Region}
  
  ApplicationURL:
    Description: URL to the Elastic Beanstalk environment
    Value: !Sub http://${ElasticBeanstalkEnvironment}.${AWS::Region}.elasticbeanstalk.com
    
  GitHubSetupInstructions:
    Description: Connecting CodeBuild to GitHub
    Value: "In the AWS Console, navigate to CodeBuild > Projects > visitor-app-build > Edit > Source > Edit, then choose GitHub as the source provider, connect to your GitHub account, and specify the repo and branch."
    
  DeploymentInstructions:
    Description: Manual deployment instructions
    Value: "1. Connect CodeBuild to GitHub using the instructions above. 2. Start a build in the CodeBuild console. 3. This will deploy to Elastic Beanstalk automatically."